baseURL: https://hawhh.de/
DefaultContentLanguage: de
enableGitInfo: true
languageCode: de
metaDataFormat: "yaml"
pygmentsCodeFences: true
pygmentsUseClasses: true
title: Inoffizielle HAW Hamburg Suche

server:
  headers:
  - for: /**
    values:
      Content-Security-Policy: base-uri 'none'; form-action 'none'; default-src 'none'; img-src 'self'; manifest-src 'self'; script-src 'self'; style-src 'self'; connect-src 'self'
